import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-deep": "var(--bg-deep)",
        "bg-layer-1": "var(--bg-layer-1)",
        "bg-layer-2": "var(--bg-layer-2)",
        "glass-tint": "var(--glass-tint)",
        "glass-border": "var(--glass-border)",
        "purple-primary": "var(--purple-primary)",
        "purple-bright": "var(--purple-bright)",
        "purple-vivid": "var(--purple-vivid)",
        "purple-pink": "var(--purple-pink)",
        "purple-deep": "var(--purple-deep)",
        "gold-rare": "var(--gold-rare)",
        "cyan-primary": "var(--cyan-primary)",
        "cyan-bright": "var(--cyan-bright)",
        "text-primary": "var(--text-primary)",
        "text-body": "var(--text-body)",
        "text-secondary": "var(--text-secondary)",
        "text-dim": "var(--text-dim)",
        "text-accent": "var(--text-accent)",
        // chatui.md (M3 dark) — used by /chat
        "on-primary": "#3c0091",
        "on-primary-container": "#340080",
        "on-surface-variant": "#cbc3d7",
        "primary-fixed": "#e9ddff",
        "surface-container-highest": "#37333d",
        "surface-tint": "#d0bcff",
        "outline-variant": "#494454",
        "on-secondary": "#313031",
        "surface-bright": "#3b3742",
        background: "#15121b",
        "surface-container-low": "#1d1a23",
        "surface-container-lowest": "#0f0d15",
        "inverse-primary": "#6d3bd7",
        "on-primary-fixed-variant": "#5516be",
        "inverse-on-surface": "#322f39",
        outline: "#958ea0",
        "on-secondary-container": "#bab8b9",
        "tertiary-fixed-dim": "#c8c5cb",
        "on-tertiary-fixed-variant": "#47464b",
        "on-tertiary-fixed": "#1b1b1f",
        "tertiary-fixed": "#e4e1e7",
        "secondary-fixed": "#e5e2e3",
        "surface-container-high": "#2c2832",
        "on-surface": "#e7e0ed",
        "surface-dim": "#15121b",
        tertiary: "#c8c5cb",
        "on-secondary-fixed-variant": "#474647",
        primary: "#d0bcff",
        "surface-container": "#211e27",
        "on-primary-fixed": "#23005c",
        "on-error-container": "#ffdad6",
        surface: "#15121b",
        "secondary-container": "#4a494a",
        "error-container": "#93000a",
        "primary-container": "#a078ff",
        "on-tertiary": "#303034",
        "primary-fixed-dim": "#d0bcff",
        error: "#ffb4ab",
        "on-secondary-fixed": "#1c1b1c",
        "on-error": "#690005",
        "surface-variant": "#37333d",
        "tertiary-container": "#919095",
        "inverse-surface": "#e7e0ed",
        "on-tertiary-container": "#29292d",
        "on-background": "#e7e0ed",
        secondary: "#c8c6c7",
        "secondary-fixed-dim": "#c8c6c7",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        glow: "var(--shadow-glow)",
      },
      fontFamily: {
        primary: "var(--font-primary)",
        verse: "var(--font-verse)",
        logo: "var(--font-logo-zh)",
      },
      transitionDuration: {
        instant: "100ms",
        quick: "200ms",
        smooth: "300ms",
        slow: "500ms",
        ornate: "1000ms",
        epic: "2500ms",
      },
    },
  },
  plugins: [typography],
};

export default config;
