import Link from "next/link";
import { Suspense } from "react"; // 新增：导入 Suspense
import type { Metadata } from "next";

import { MarketingLanguageSwitcher } from "@/components/marketing/marketing-language-switcher";
import { MarketingLocaleProvider } from "@/components/marketing/marketing-locale";
import { PojuMarkLogo } from "@/components/marketing/poju-mark-logo";

// 1. 强制动态渲染，防止 Build 时的 Prerender 错误
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Terms of Service — POJU",
  description: "POJU terms of service",
};

const terms = [
  "1. Use of Services",
  "2. No Guarantees",
  "3. Payments",
  "4. Refunds",
  "5. Changes to These Terms",
  "6. Intellectual Property",
  "7. Limitation of Liability",
  "8. Governing Law",
] as const;

const termsOriginalBlocks = [
  `By accessing or using POJU, Syncro, or Glyph (collectively, 
"the Services"), you agree to these Terms of Service.

POJU provides AI-powered insights drawing from Eastern 
philosophical traditions. The Services are for lawful personal 
use only.

You agree not to:
· Use the Services for commercial purposes without permission
· Attempt to reverse-engineer, scrape, or systematically 
  access the Services
· Use the Services to harass, defame, or harm others
· Submit illegal, threatening, or harmful content
· Impersonate others or misrepresent your identity`,
  `We do not guarantee any specific results. 
All outputs are generated by AI models trained on 
Eastern philosophical texts and modern research.

POJU cannot predict the future, diagnose conditions, 
or resolve complex personal situations. The Services are 
for reflection and self-exploration.

See our Disclaimer (/disclaimer) for full details.`,
  `POJU Breakthrough Sessions cost US$9.99 per session, 
charged once.

Syncro and Glyph are free and always will be.

· All payments are one-time only. No subscriptions.
· No automatic renewals. No hidden charges.
· Prices may change; you'll see the price before payment.
· Payment is handled by Stripe (or an alternative processor).
  We never see your card details.

Your POJU Session, once purchased, stays accessible on your 
device until you manually end it. There is no expiration.`,
  `We offer refunds under the following conditions:

· Technical failure prevented you from accessing your Session: 
  full refund within 7 days of purchase
· You have not yet started the conversation: full refund 
  within 24 hours
· Duplicate charge (paid twice by mistake): full refund

We do not offer refunds for:
· "The insights weren't what I expected" — AI outputs are 
  inherently subjective
· "I changed my mind after starting" — once a Session is 
  active, the service has been delivered
· Requests after 7 days from purchase

To request a refund, email support@pojulife.com with your 
Stripe payment ID.

Refunds typically process within 5-10 business days.`,
  `We may update these Terms at any time. 

For material changes (e.g., new fees, significant 
restrictions), we will:
· Notify you via in-app banner on next visit
· Require re-agreement before continuing

For minor changes (typo corrections, clarifications):
· Update the "Last updated" date
· No active notification required

Continued use of the Services after changes constitutes 
acceptance.`,
  `The POJU brand, logo, "Three ways in. One way through." 
tagline, and all product interface elements are owned by 
POJU. You may not copy, modify, or redistribute them.

Content generated for your personal Session (e.g., AI 
responses, PDF reports) is yours to use personally. You 
may not republish AI-generated outputs as your own work 
or for commercial purposes.

Eastern philosophical texts referenced (Daoism, I Ching, 
Feng Shui principles) are in the public domain.`,
  `To the maximum extent permitted by law:

· The Services are provided "as is"
· We are not liable for decisions, actions, or outcomes 
  resulting from use of our outputs
· Our total liability in any claim is limited to the amount 
  you paid in the past 12 months (typically $9.99 per session)

See our Disclaimer for full details.`,
  `These Terms are governed by the laws of [州名待律师确定，
推荐 Delaware], United States, without regard to conflict 
of law principles.

Any disputes will be resolved in the courts of [地点待律师].

If you're in the EU and mandatory local law applies, your 
statutory rights remain intact.`,
] as const;

// 2. 将原页面逻辑移至 Content 组件
function TermsContent() {
  return (
    <MarketingLocaleProvider>
      <main className="bg-bg-deep text-text-body">
        <div className="w-full px-3 pb-10 pt-4 sm:px-4 sm:pt-6 md:px-6 md:pb-12">
          <header className="px-1 py-2.5 sm:py-3 md:px-2">
            <div className="mx-auto flex w-full max-w-6xl items-center justify-between">
              <Link href="/" className="inline-flex items-center gap-0">
                <PojuMarkLogo />
                <span className="inline-flex items-center text-[14px] font-semibold leading-none tracking-[0.09em] text-text-primary sm:text-[15px] md:text-[16px]">
                  POJU
                </span>
              </Link>
              <nav className="hidden items-center gap-7 text-[12px] uppercase tracking-[0.12em] text-text-secondary sm:text-[13px] md:flex md:text-[14px]">
                <Link href="/poju" className="hover:text-text-primary">
                  POJU 破局
                </Link>
                <Link href="/syncro" className="hover:text-text-primary">
                  POJU SYNCRO
                </Link>
                <Link href="/glyph" className="hover:text-text-primary">
                  POJU GLYPH
                </Link>
                <Link href="/archive" className="hover:text-text-primary">
                  THE ARCHIVE
                </Link>
              </nav>
              <MarketingLanguageSwitcher />
            </div>
          </header>

          <section className="mx-auto mt-2 w-full max-w-4xl rounded-2xl border border-white/10 bg-black/25 px-5 py-8 sm:px-7 md:px-10">
            <p className="text-center text-xs uppercase tracking-[0.16em] text-text-dim">Version 1.0</p>
            <h1 className="mt-3 text-center text-[28px] font-semibold text-text-primary sm:text-[34px]">
              Terms of Service
            </h1>
            <p className="mt-2 text-center text-sm text-text-dim">Last updated: [日期]</p>

            <div className="mt-8 space-y-6">
              {terms.map((item, idx) => (
                <article key={item} className="rounded-xl border border-white/8 bg-white/[0.02] px-4 py-4 sm:px-5">
                  <h2 className="text-[16px] font-semibold text-text-primary sm:text-[17px]">{item}</h2>
                  <pre className="mt-2 whitespace-pre-wrap text-[14px] leading-7 text-text-secondary sm:text-[15px]">
                    {termsOriginalBlocks[idx]}
                  </pre>
                </article>
              ))}
            </div>

            <pre className="mt-8 whitespace-pre-wrap text-center text-[14px] leading-7 text-text-secondary sm:text-[15px]">
              {"Questions about these Terms?\nlegal@pojulife.com\n\nGeneral support:\nsupport@pojulife.com"}
            </pre>
          </section>

          <footer className="mt-8 w-full rounded-xl bg-bg-layer-1/60 px-4 py-6 md:px-8">
            <div className="mx-auto max-w-6xl text-center">
              <p className="text-lg font-semibold tracking-[0.12em] text-text-primary">POJU</p>
              <p className="mt-1 text-sm text-text-secondary">pojulife.com</p>
              <div className="my-4 h-px bg-gradient-to-r from-transparent via-glass-border to-transparent" />
              <div className="flex flex-wrap items-center justify-center gap-4 text-sm text-text-secondary">
                <Link href="/" className="hover:text-text-primary">
                  Home
                </Link>
                <Link href="/disclaimer" className="hover:text-text-primary">
                  Disclaimer
                </Link>
                <Link href="/privacy" className="hover:text-text-primary">
                  Privacy Policy
                </Link>
                <Link href="/terms" className="hover:text-text-primary">
                  Terms of Service
                </Link>
                <Link href="/contact" className="hover:text-text-primary">
                  Contact
                </Link>
              </div>
              <p className="mt-4 text-center text-xs text-text-dim">© 2026 POJU. All rights reserved.</p>
              <p className="mt-2 text-center text-xs text-text-dim">
                For reflection and entertainment. POJU does not predict outcomes or replace professional advice.
              </p>
            </div>
          </footer>
        </div>
      </main>
    </MarketingLocaleProvider>
  );
}

// 3. 默认导出入口，包裹 Suspense
export default function TermsPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-bg-deep" />}>
      <TermsContent />
    </Suspense>
  );
}