import { Suspense } from "react";
import type { Metadata } from "next";
import { Link } from "@/i18n/navigation";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Terms of Service — POJU",
  description: "POJU terms of service",
};

function TermsContent() {
  return (
    <main className="bg-bg-deep text-text-body">
      <div className="w-full px-3 pb-10 pt-4 sm:px-4 sm:pt-6 md:px-6 md:pb-12">
        <section className="prose prose-invert prose-lg mx-auto mt-2 max-w-4xl rounded-2xl border border-white/10 bg-black/25 px-5 py-8 text-text-secondary prose-headings:text-text-primary prose-a:text-purple-vivid sm:px-7 md:px-10">
          <p className="text-center text-xs uppercase tracking-[0.16em] text-text-dim not-prose">Version 1.0</p>
          <h1 className="mt-3 text-center text-text-primary not-prose text-[28px] font-semibold sm:text-[34px]">
            Terms of Service
          </h1>
          <p className="text-center text-sm text-text-dim not-prose">Last updated: October 30, 2025</p>
          <p className="not-prose mt-6 text-center text-sm text-text-secondary">
            By using POJU (pojulife.com), you agree to these Terms of Service.
          </p>

          <h2>1. Use of Services</h2>
          <p>
            By accessing or using POJU, Glyph, or Syncro (collectively, &quot;the Services&quot;), you agree to these Terms
            of Service.
          </p>
          <p>
            POJU provides AI-powered decision support drawing from philosophical and psychological frameworks (including
            Eastern philosophy, decision psychology, and behavioral economics). The Services are for lawful personal use
            only.
          </p>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Services for commercial purposes without permission</li>
            <li>Attempt to reverse-engineer, scrape, or systematically access the Services</li>
            <li>Use the Services to harass, defame, or harm others</li>
            <li>Submit illegal, threatening, or harmful content</li>
            <li>Impersonate others or misrepresent your identity</li>
          </ul>

          <h2>2. No Guarantees</h2>
          <p>
            We do not guarantee any specific results. All outputs are generated by AI models trained on philosophical texts
            and modern research.
          </p>
          <p>
            POJU cannot predict the future, diagnose conditions, or resolve complex personal situations. The Services are for
            reflection and self-exploration.
          </p>
          <p>
            See our <Link href="/disclaimer">Disclaimer</Link> for full details.
          </p>

          <h2>3. Payments</h2>
          <p>POJU Breakthrough Sessions cost US$9.99 per session, charged once.</p>
          <p>Glyph and Syncro are free and always will be.</p>
          <ul>
            <li>All payments are one-time only. No subscriptions.</li>
            <li>No automatic renewals. No hidden charges.</li>
            <li>Prices may change; you&apos;ll see the price before payment.</li>
            <li>Payment is handled by our payment processor. We never see your card details.</li>
          </ul>
          <p>
            Your POJU Session, once purchased, stays accessible on your device for 30 days. You can return anytime within that
            window to continue.
          </p>

          <h2>4. Refunds</h2>
          <p>We offer refunds under the following conditions:</p>
          <p>
            <strong>Full refund within 5 minutes of starting</strong> — Automatic. Click &quot;Refund&quot; within 5 minutes
            for an immediate full refund.
          </p>
          <p>
            <strong>Full refund for technical issues</strong> — If a technical failure prevented you from accessing your
            Session, contact <a href="mailto:support@pojulife.com">support@pojulife.com</a> within 7 days.
          </p>
          <p>
            <strong>Case-by-case review after 5 minutes</strong> — Email <a href="mailto:support@pojulife.com">support@pojulife.com</a>{" "}
            with your reason. Most reasonable requests are approved within 24 hours.
          </p>
          <p>We typically do not offer refunds for:</p>
          <ul>
            <li>
              &quot;The insights weren&apos;t what I expected&quot; — AI outputs are inherently subjective
            </li>
            <li>Substantial Session use beyond initial exploration</li>
            <li>Requests after 30 days from purchase</li>
          </ul>
          <p>
            To request a refund, email <a href="mailto:support@pojulife.com">support@pojulife.com</a> with your order ID.
          </p>
          <p>Refunds typically process within 5-10 business days, depending on your bank.</p>

          <h2>5. Changes to These Terms</h2>
          <p>We may update these Terms at any time.</p>
          <p>For material changes (e.g., new fees, significant restrictions), we will:</p>
          <ul>
            <li>Notify you via in-app banner on next visit</li>
            <li>Require re-agreement before continuing</li>
          </ul>
          <p>For minor changes (typo corrections, clarifications):</p>
          <ul>
            <li>Update the &quot;Last updated&quot; date</li>
            <li>No active notification required</li>
          </ul>
          <p>Continued use of the Services after changes constitutes acceptance.</p>

          <h2>6. Intellectual Property</h2>
          <p>
            The POJU brand, logo, &quot;Three ways in. One way through.&quot; tagline, and all product interface elements are
            owned by POJU. You may not copy, modify, or redistribute them.
          </p>
          <p>
            Content generated for your personal Session (e.g., AI responses, PDF reports) is yours to use personally. You may
            not republish AI-generated outputs as your own work or for commercial purposes.
          </p>
          <p>
            Public-domain works and classical commentary referenced in documentation are cited where applicable. POJU does not
            claim exclusive rights over traditional ideas.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law:</p>
          <ul>
            <li>The Services are provided &quot;as is&quot;</li>
            <li>We are not liable for decisions, actions, or outcomes resulting from use of our outputs</li>
            <li>
              Our total liability in any claim is limited to the amount you paid in the past 12 months (typically $9.99 per
              session)
            </li>
          </ul>
          <p>
            See our <Link href="/disclaimer">Disclaimer</Link> for full details.
          </p>

          <h2>8. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law
            principles.
          </p>
          <p>Any disputes will be resolved in the courts of Delaware.</p>
          <p>If you&apos;re in the EU and mandatory local law applies, your statutory rights remain intact.</p>

          <h2>Contact</h2>
          <p>
            Questions about these Terms? <a href="mailto:legal@pojulife.com">legal@pojulife.com</a>
            <br />
            General support: <a href="mailto:support@pojulife.com">support@pojulife.com</a>
          </p>
        </section>
      </div>
    </main>
  );
}

export default function TermsPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-bg-deep" />}>
      <TermsContent />
    </Suspense>
  );
}
