import type { Metadata } from "next";

import { LegalPageShell } from "@/components/legal/legal-page-shell";
import { Link } from "@/i18n/navigation";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Terms of Service — pojulife",
  description: "pojulife terms of service — Version 1.1",
};

export default function TermsPage() {
  return (
    <LegalPageShell
      version="Version 1.1"
      title="Terms of Service"
      updated="Last updated: 2026-06-15"
      intro={
        <p>
          <strong>Governing Language:</strong> This agreement is formulated and executed exclusively in the English
          language. Any localized translations provided elsewhere are for convenience only, and this English version
          shall govern and prevail in all aspects of interpretation and dispute resolution.
        </p>
      }
    >
      <h2>Welcome to pojulife</h2>
      <p>
        pojulife (pojulife.com) and its modular decision-support engines—POJU, Glyph, Syncro, and Match (collectively,
        &quot;the Services&quot;)—are operated by Tonghui Chen, an individual developer based in the People&apos;s
        Republic of China (&quot;we&quot;, &quot;us&quot;, and &quot;our&quot;).
      </p>
      <p>
        By accessing, browsing, initiating a session, or executing a transaction within the Services, you confirm that
        you have read, understood, and unreservedly agree to be legally bound by these Terms of Service
        (&quot;Terms&quot;). If you do not agree to these Terms, you must immediately cease utilizing the platform.
      </p>

      <h2>1. Eligibility and Lawful Use</h2>
      <ul>
        <li>
          <strong>Age Framework:</strong> The Services are engineered strictly for personal, adult exploration. You
          must be at least 18 years of age or older to purchase single tokens, activate active sessions, or subscribe to
          billing plans.
        </li>
        <li>
          <strong>Prohibited Conduct:</strong> You explicitly agree not to:
          <ul>
            <li>
              Attempt to scrape, decompile, reverse-engineer, or systematically harvest the underlying algorithmic API
              architectures or source code of pojulife.
            </li>
            <li>
              Deploy automated bots, script-injected queries, or high-frequency automated traffic to bypass processing
              guardrails.
            </li>
            <li>Exploit the platform to generate illegal, threatening, or harmful textual data.</li>
            <li>
              Utilize the proprietary analytical frameworks or outputs for institutional commercialization without
              explicit prior written authorization from the operator.
            </li>
          </ul>
        </li>
      </ul>

      <h2>2. Nature and Evolution of the Services</h2>
      <p>
        pojulife provides advanced cognitive reframing tools powered by generative intelligence models. You acknowledge
        and agree that:
      </p>
      <ul>
        <li>
          <strong>Probabilistic Outputs:</strong> Content generated by our engines is inherently non-deterministic and
          probabilistic. Algorithmic insights are designed exclusively as lenses for cognitive modeling and structured
          contemplation.
        </li>
        <li>
          <strong>No Substitution for Professional Advice:</strong> The Services do not provide legal, psychiatric,
          financial, tax, or medical counseling. You hold 100% personal accountability for any real-world decisions or
          lifestyle changes implemented following your platform interactions. (Please read our full{" "}
          <Link href="/disclaimer">Disclaimer</Link> for granular statutory exclusions).
        </li>
      </ul>

      <h2>3. Financial Infrastructure, Billing, and Subscription Framework</h2>
      <p>
        By initiating a checkout, you agree to the pricing matrix active at the moment of your session request.
        Payments are processed via secure cryptographic routing.
      </p>

      <h3>A. Dual Transactional Architecture</h3>
      <p>We provision two distinct commercial engagement models:</p>
      <ol>
        <li>
          <strong>Pay-Per-Use (Standalone Tokens):</strong>
          <ul>
            <li>
              <strong>POJU:</strong> US$9.99 per single session initialization. Grants 30 days of conversational access
              to the specific query thread, structurally archived within your local browser&apos;s storage matrix.
            </li>
            <li>
              <strong>Glyph / Syncro / Match:</strong> US$4.99 per independent engine activation or programmatic
              spatiotemporal matrix generation.
            </li>
          </ul>
        </li>
        <li>
          <strong>Monthly Pass Subscription Plan:</strong>
          <ul>
            <li>
              <strong>Ecosystem Allocation:</strong> At a recurring rate of <strong>US$29.99 per month</strong>,
              subscribers are systematically provisioned an absolute ecosystem voucher pack valued at US$125. Each monthly
              billing renewal deploys 5× POJU session tokens, 5× Glyph tokens, 5× Match tokens, and 5× Syncro tokens to
              your localized identity.
            </li>
            <li>
              <strong>Recurring Billing:</strong> By selecting the Monthly Pass option, you grant explicit authorization
              to our designated payment processors to automatically debit the recurring subscription fee from your
              optioned credit card or digital wallet at the start of each billing cycle.
            </li>
          </ul>
        </li>
      </ol>

      <h3>B. Absolute Anti-Dark-Pattern Subscription Control</h3>
      <ul>
        <li>
          <strong>Single-Click Cancellation:</strong> We reject predatory retaining loops. You maintain absolute
          jurisdiction over your subscription. You can cancel your automated Monthly Pass renewal at any time with a
          single click via your secure checkout portal or by messaging billing notifications to{" "}
          <a href="mailto:support@pojulife.com">support@pojulife.com</a>.
        </li>
        <li>
          <strong>Service Continuance:</strong> Upon cancellation of your Monthly Pass, your premium token allotment
          will remain fully active and executable until the official conclusion of your current paid billing cycle. No
          partial mid-month refunds are authorized.
        </li>
      </ul>

      <h3>C. Payment Processing and Merchant of Record (MOR)</h3>
      <p>
        All international credit card processing, local wallet handshakes, and subscription management are securely
        executed by <strong>Dodo Payments</strong> (or its global affiliates) acting as our authorized{" "}
        <strong>Merchant of Record (MOR)</strong>. pojulife never stores, logs, or views your raw credit card numbers.
        Your formal transaction receipt and banking line item will designate Dodo Payments as the legal seller of record
        for the transaction.
      </p>

      <h2>4. Refund Policy Overview</h2>
      <p>
        Transactions executed across pojulife are strictly protected and bounded by our dedicated{" "}
        <Link href="/refund">Refund Policy</Link>. In summary:
      </p>
      <ul>
        <li>
          Full refunds are issued within 7 days for verified technical delivery failures caused entirely by internal
          platform exceptions.
        </li>
        <li>
          No refunds or chargeback reversals will be authorized based on personal dissatisfaction with AI linguistic
          styling, variations in subjective analytical interpretations, or simple changes of mind once tokens have been
          programmatically spent.
        </li>
      </ul>

      <h2>5. Proprietary Property and Intellectual Rights</h2>
      <ul>
        <li>
          <strong>Our Core IP:</strong> The logos, the structural &quot;pojulife&quot; interface, our custom branding
          vectors, the custom <strong>Five Wind cards</strong> architecture (<em>
            Divine Tailwind, Fair Sky, Still Water, Crosswind, Eye of Storm
          </em>
          ), and the structural <strong>Five Current categories</strong> (<em>
            Open Current, Following Current, Stillwater, Crosscurrent, Undertow
          </em>
          ) are the exclusive intellectual property of Tonghui Chen. Any unauthorized replication, institutional
          licensing, or external system injection is strictly prohibited.
        </li>
        <li>
          <strong>Your Generated Outputs:</strong> The localized textual reflections assembled inside your active
          sessions belong to you for private personal utility. You may quote, journal, or share your individual results
          for non-commercial personal expression. You may not mass-distribute generated outputs to train external
          competing linguistic models or sell outputs for commercial gain.
        </li>
        <li>
          <strong>Public Domain Assets:</strong> Classical historical texts referenced during contextual computations
          (e.g., historical editions of the <em>I Ching</em> or public domain strategic maxims) belong entirely to the
          public domain. We assert no ownership over classical public texts.
        </li>
      </ul>

      <h2>6. Account Architecture and Local Data Custody</h2>
      <p>pojulife utilizes a decentralized user-state architecture:</p>
      <ul>
        <li>
          <strong>No Cloud Identity Vaults:</strong> We do not mandate registration via email/password combos or OAuth
          third-party cloud trackers.
        </li>
        <li>
          <strong>Localized Cache Custody:</strong> Your complete conversation logs are fully encrypted (via AES-256
          protocols) and saved exclusively inside your browser&apos;s IndexedDB environment.
        </li>
        <li>
          <strong>Session Tracking:</strong> A cryptographic, one-way hash of your hardware profile (Device
          Fingerprint) is utilized as a silent anchor to validate subscription structures and active token authorization
          balances.
        </li>
        <li>
          <strong>Data Loss Exclusion:</strong> Because data lives strictly on your personal device, we hold no
          liability for data clearance resulting from manual browser wipes, local hardware corruption, privacy extensions
          clearing local data, or device loss.
        </li>
      </ul>

      <h2>7. Global Limitation of Liability</h2>
      <p>To the absolute maximum extent permitted under applicable jurisdictions:</p>
      <ul>
        <li>
          The Services are deployed on an &quot;As-Is&quot; and &quot;As-Available&quot; engineering baseline without
          warranties of any nature.
        </li>
        <li>
          The operator (Tonghui Chen) shall not be liable for indirect, incidental, existential, consequential, or
          punitive damages—including capital losses, emotional strain, or relationship adjustments—connected to platform
          use.
        </li>
        <li>
          Our total cumulative liability for any verified legal claim arising out of these terms shall be strictly capped
          at the total financial amount you actively paid to pojulife during the immediate twelve (12) months preceding
          the claim event.
        </li>
      </ul>

      <h2>8. Dispute Resolution and Governing Jurisdiction</h2>
      <p>
        These Terms shall be interpreted and governed strictly in accordance with the laws of the People&apos;s Republic
        of China, bypassing any conflict-of-law principles.
      </p>
      <p>
        Any formal litigation or legal controversy arising out of these terms shall be submitted to the exclusive
        jurisdictional courts located within the operator&apos;s place of legal residence in China. For consumers
        accessing the service from the European Economic Area (EEA), the United Kingdom, or regions with mandatory
        statutory consumer preservation acts, your local consumer forum rights remain active where local laws mandate
        precedence.
      </p>

      <h2>9. Operational Communication Nodes</h2>
      <p>For immediate resolution of legal, operational, or technical issues, deploy formal correspondence to our dedicated nodes:</p>
      <ul>
        <li>
          <strong>Legal Compliance &amp; Gateway Disputes:</strong>{" "}
          <a href="mailto:legal@pojulife.com">legal@pojulife.com</a>
        </li>
        <li>
          <strong>Subscription Operations &amp; Token Validation:</strong>{" "}
          <a href="mailto:support@pojulife.com">support@pojulife.com</a>
        </li>
        <li>
          <strong>Data Rectification &amp; Privacy Inquiries:</strong>{" "}
          <a href="mailto:privacy@pojulife.com">privacy@pojulife.com</a>
        </li>
      </ul>
    </LegalPageShell>
  );
}
